 [platformio]
build_dir = C:/pio_build/els-7e2-lcd2004

[env:black_f407ze]
platform = ststm32
board = black_f407ze
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink
board_build.f_cpu = 168000000L
; Ручний енкодер: -D HAND_ENCODER_SOFTWARE_QUAD=0, -D HAND_ENC_INVERT=1, -D HAND_ENCODER_DISPLAY_RAW_PER_DETENT=2|4 (лише LCD)
build_flags =
    -D F_CPU=168000000L
lib_deps =
    https://github.com/johnrickman/LiquidCrystal_I2C.git

; Додаткові налаштування для USB Serial (за бажанням)
; build_flags = 
;     -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
;     -D USBCON
