[env:black_f407ze]
platform = ststm32
board = black_f407ze
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 168000000L
build_flags =
    -D F_CPU=168000000L
lib_deps =
    arduino-libraries/LiquidCrystal

; Додаткові налаштування для USB Serial (за бажанням)
; build_flags = 
;     -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
;     -D USBCON
